
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Zika EKS Cluster'

Parameters:
  EKSClusterName:
    Type: String
    Default: zika-cluster
    Description: EKS Cluster Name
  eksClusterRoleArn:
    Type: String
    Default: "arn:aws:iam::395229015146:role/zika-stack-Roles-XELEMDRNX8IG-eksClusterRole-1C0UGOA8436ZU"
    Description: EKS Cluster Role Arn
  Subnet01ID:
    Type: String
    Default: ""
    Description: Subnet 1
  Subnet02ID:
    Type: String
    Default: ""
    Description: Subnet 2
  NodeInstanceRoleArn:
    Type: String
    Default: ""
    Description: NodeInstanceRoleArn
  ControlPlaneSecurityGroup:
    Type: String
    Default: ""
    Description: ControlPlaneSecurityGroup

Resources:
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      Version: '1.17'
      RoleArn: !Ref eksClusterRoleArn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds:
          - !Ref Subnet01ID
          - !Ref Subnet02ID

  # EKSNodegroup:
  #   Type: AWS::EKS::Nodegroup
  #   DependsOn: Cluster
  #   Properties:
  #     AmiType: 'AL2_x86_64'
  #     ClusterName: !Ref EKSClusterName
  #     NodegroupName: 'private-nodes'
  #     NodeRole: !Ref NodeInstanceRoleArn
  #     RemoteAccess:
  #       Ec2SshKey: 'zika' 
  #       SourceSecurityGroups: [!Ref ControlPlaneSecurityGroup]
  #     InstanceTypes: ['t3.medium']
  #     ScalingConfig:
  #       MinSize: 1
  #       DesiredSize: 1
  #       MaxSize: 2
  #     Subnets:
  #       - !Ref Subnet01ID
  #       - !Ref Subnet02ID

Outputs:
    eksClusterId:
      Description: The EKS Cluster Id
      Value: !Ref Cluster
    # NodeGroupId:
    #   Description: The EKS node group Id
    #   Value: !Ref EKSNodegroup
