AWSTemplateFormatVersion: '2010-09-09'
Description: Zika stack master stack
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/zika-cloudformation/ad632838873b49c2731c7a0c887cae2f.template
  Roles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/zika-cloudformation/9f11934660fc87061aae8f47a69e7e52.template
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/zika-cloudformation/7e344c65f1f4fabceeb97bff5ac9f0db.template
      Parameters:
        Subnet01ID:
          Fn::GetAtt:
          - Network
          - Outputs.Subnet01ID
        Subnet02ID:
          Fn::GetAtt:
          - Network
          - Outputs.Subnet02ID
        ControlPlaneSecurityGroup:
          Fn::GetAtt:
          - Network
          - Outputs.ControlPlaneSecGp
        eksClusterRoleArn: arn:aws:iam::395229015146:role/zika-stack-Roles-XELEMDRNX8IG-eksClusterRole-1C0UGOA8436ZU
        NodeInstanceRoleArn:
          Fn::GetAtt:
          - Roles
          - Outputs.eksNodeRole
